const KEY="pusatku-v3";
const blank={finance:[],tasks:[],reminders:[],shopping:[],inventory:[],notes:[],fish:[]};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(blank); for(const k in blank) db[k] ||= [];
db.cloud=db.cloud||{url:"https://pusatku-keuanganku-sync.adityapm43211.workers.dev",key:"",enabled:false,lastSync:0};
const CLOUD_DEFAULT="https://pusatku-keuanganku-sync.adityapm43211.workers.dev";
let cloudTimer=null,cloudBusy=false;
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const dateText=d=>d?new Date(d).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"}):"";
function persist(){localStorage.setItem(KEY,JSON.stringify(db));render();}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2200)}
function empty(msg){return `<div class="empty">${esc(msg)}</div>`}
function row(title,sub,k,id,mode="delete"){return `<div class="item"><div><div class="title">${title}</div><div class="sub">${sub}</div></div><div class="item-actions">${mode==="toggle"?`<button data-toggle="${k}" data-id="${id}">${db[k].find(x=>x.id===id)?.done?"Buka":"Selesai"}</button>`:""}<button class="danger" data-delete="${k}" data-id="${id}">Hapus</button></div></div>`}
function render(){
 const inc=db.finance.filter(x=>x.type==="in").reduce((a,x)=>a+Number(x.amount),0), out=db.finance.filter(x=>x.type==="out").reduce((a,x)=>a+Number(x.amount),0), bal=inc-out;
 $("#balance").textContent=money(bal);$("#income").textContent="+ "+money(inc);$("#expense").textContent="− "+money(out);
 $("#financeIncome").textContent=money(inc);$("#financeExpense").textContent=money(out);$("#financeIncome2").textContent=money(inc);$("#financeExpense2").textContent=money(out);$("#financeBalance2").textContent=money(bal);
 $("#taskCount").textContent=db.tasks.filter(x=>!x.done).length;$("#reminderCount").textContent=db.reminders.filter(x=>!x.done).length;$("#inventoryCount").textContent=db.inventory.reduce((a,x)=>a+Number(x.qty||0),0);
 if($("#cloudStatus")){const c=cloudConfig();$("#cloudStatus").textContent=cloudConfigured()?"☁️ Terhubung":"Belum terhubung";$("#cloudLastSync").textContent=c.lastSync?`Terakhir sync: ${new Date(c.lastSync).toLocaleString("id-ID")}`:"Belum pernah sinkronisasi";if($("#cloudKey")&&document.activeElement!==$("#cloudKey"))$("#cloudKey").value=c.key||""}const max=Math.max(inc,out,1);$("#incomeBar").style.width=(inc/max*100)+"%";$("#expenseBar").style.width=(out/max*100)+"%";$("#chartIn").style.width=(inc/max*100)+"%";$("#chartOut").style.width=(out/max*100)+"%";
 $("#monthLabel").textContent=new Date().toLocaleDateString("id-ID",{month:"long",year:"numeric"});
 $("#financeList").innerHTML=db.finance.slice().reverse().map(x=>row(`${x.type==="in"?"＋":"−"} ${esc(x.title)}`,money(x.amount),"finance",x.id)).join("")||empty("Belum ada transaksi.");
 $("#taskList").innerHTML=db.tasks.map(x=>row(`${x.done?"☑":"☐"} ${esc(x.title)}`,x.due?dateText(x.due):"Tanpa tenggat","tasks",x.id,"toggle")).join("")||empty("Belum ada tugas.");
 $("#reminderList").innerHTML=db.reminders.map(x=>row(`⏰ ${esc(x.title)}`,dateText(x.when),"reminders",x.id,"toggle")).join("")||empty("Belum ada pengingat.");
 $("#shoppingList").innerHTML=db.shopping.map(x=>row(`${x.done?"☑":"🛒"} ${esc(x.title)}`,`Jumlah: ${esc(x.qty||1)}`,"shopping",x.id,"toggle")).join("")||empty("Daftar belanja kosong.");
 $("#inventoryList").innerHTML=db.inventory.map(x=>row(`📦 ${esc(x.title)}`,`Stok: ${esc(x.qty)} · Minimum: ${esc(x.min||0)}`,"inventory",x.id)).join("")||empty("Belum ada barang.");
 $("#noteList").innerHTML=db.notes.map(x=>row(`📝 ${esc(x.title)}`,esc(x.body).slice(0,100),"notes",x.id)).join("")||empty("Belum ada catatan.");
 $("#recent").innerHTML=db.finance.slice().reverse().slice(0,4).map(x=>row(`${x.type==="in"?"＋":"−"} ${esc(x.title)}`,money(x.amount),"finance",x.id)).join("")||empty("Belum ada aktivitas.");
 const low=db.inventory.filter(x=>Number(x.qty)<=Number(x.min||0));$("#attention").innerHTML=low.map(x=>`<div class="item"><div><div class="title">⚠️ ${esc(x.title)}</div><div class="sub">Stok ${esc(x.qty)} · minimum ${esc(x.min||0)}</div></div></div>`).join("")||empty("Semua stok aman.");
 $("#fishList").innerHTML=db.fish.map(x=>`<article class="fish-card"><div class="fish-icon">🐟</div><h3>${esc(x.name)}</h3><p>${esc(x.species||"Jenis belum diisi")}</p><div class="fish-meta"><span>${esc(x.qty||0)} ekor</span><span>${esc(x.size||"Ukuran —")}</span><span>${esc(x.color||"Warna —")}</span><span>Motif: ${esc(x.pattern||"—")}</span><span>📍 ${esc(x.tank||"—")}</span></div><p>${esc(x.note||"Tidak ada catatan")}</p><div class="item-actions"><button class="danger" data-delete="fish" data-id="${x.id}">Hapus</button></div></article>`).join("")||empty("Belum ada data ikan.");
 $("#statTransactions").textContent=db.finance.length;$("#statFish").textContent=db.fish.reduce((a,x)=>a+Number(x.qty||0),0);$("#statDone").textContent=db.tasks.filter(x=>x.done).length;$("#statNotes").textContent=db.notes.length;
}
function show(page){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===page));document.querySelectorAll("[data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page===page));window.scrollTo({top:0,behavior:"smooth"})}
const input=(name,label,type="text",extra="")=>`<div class="field"><label>${label}</label><input name="${name}" type="${type}" ${extra} required></div>`;
function modal(title,fields,submit){$("#modalTitle").textContent=title;$("#form").innerHTML=fields+`<button class="submit">Simpan data</button>`;$("#modal").classList.remove("hidden");$("#form").onsubmit=e=>{e.preventDefault();submit(new FormData(e.target));$("#modal").classList.add("hidden");persist();toast("Data berhasil disimpan");}}
function action(a){
 if(a==="add-finance")modal("Tambah transaksi",input("title","Keterangan")+input("amount","Jumlah","number","min='0'")+`<div class="field"><label>Jenis</label><select name="type"><option value="out">Pengeluaran</option><option value="in">Pemasukan</option></select></div>`,f=>db.finance.push({id:uid(),title:f.get("title"),amount:+f.get("amount"),type:f.get("type"),at:new Date().toISOString()}));
 if(a==="add-task")modal("Tambah tugas",input("title","Nama tugas")+input("due","Tenggat","datetime-local"),f=>db.tasks.push({id:uid(),title:f.get("title"),due:f.get("due"),done:false}));
 if(a==="add-reminder")modal("Tambah pengingat",input("title","Isi pengingat")+input("when","Waktu","datetime-local"),f=>db.reminders.push({id:uid(),title:f.get("title"),when:f.get("when"),done:false,notified:false}));
 if(a==="add-shopping")modal("Tambah belanja",input("title","Nama barang")+input("qty","Jumlah","number","min='1' value='1'"),f=>db.shopping.push({id:uid(),title:f.get("title"),qty:+f.get("qty"),done:false}));
 if(a==="add-inventory")modal("Tambah inventaris",input("title","Nama barang")+input("qty","Stok","number","min='0'")+input("min","Stok minimum","number","min='0'"),f=>db.inventory.push({id:uid(),title:f.get("title"),qty:+f.get("qty"),min:+f.get("min")}));
 if(a==="add-fish")modal("Tambah log ikan",input("name","Nama ikan")+input("species","Jenis / spesies")+input("qty","Jumlah","number","min='0'")+input("size","Ukuran")+input("color","Warna")+input("pattern","Motif")+input("tank","Aquarium / lokasi")+`<div class="field"><label>Catatan</label><textarea name="note" rows="4"></textarea></div>`,f=>db.fish.push({id:uid(),name:f.get("name"),species:f.get("species"),qty:+f.get("qty"),size:f.get("size"),color:f.get("color"),pattern:f.get("pattern"),tank:f.get("tank"),note:f.get("note")}));
 if(a==="add-note")modal("Tambah catatan",input("title","Judul")+`<div class="field"><label>Isi</label><textarea name="body" rows="5" required></textarea></div>`,f=>db.notes.push({id:uid(),title:f.get("title"),body:f.get("body")}));
}
function backup(){const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`PusatKu-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);toast("Backup berhasil dibuat")}
function restore(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);for(const k in blank)if(!Array.isArray(x[k]))throw Error();db=x;persist();toast("Restore berhasil") }catch{toast("File backup tidak valid")}};r.readAsText(file)}
function checkReminders(){if(!("Notification"in window)||Notification.permission!=="granted")return;const now=Date.now();let changed=false;db.reminders.filter(x=>!x.done&&!x.notified&&new Date(x.when).getTime()<=now).forEach(x=>{try{new Notification("PusatKu",{body:x.title,icon:"icon.svg"})}catch{}x.notified=true;changed=true});if(changed)localStorage.setItem(KEY,JSON.stringify(db))}
async function enableNotify(){if(!("Notification"in window)){toast("Browser tidak mendukung notifikasi");return}const p=await Notification.requestPermission();toast(p==="granted"?"Notifikasi aktif":"Izin notifikasi belum diberikan")}

document.addEventListener("click",e=>{const p=e.target.closest("[data-page]");if(p)show(p.dataset.page);const a=e.target.closest("[data-action]");if(a)action(a.dataset.action);const d=e.target.closest("[data-delete]");if(d){db[d.dataset.delete]=db[d.dataset.delete].filter(x=>x.id!==d.dataset.id);persist();toast("Data dihapus")};const t=e.target.closest("[data-toggle]");if(t){const x=db[t.dataset.toggle].find(x=>x.id===t.dataset.id);if(x){x.done=!x.done;persist();toast(x.done?"Ditandai selesai":"Dibuka kembali")}}});
$("#quickAdd").onclick=()=>action("add-task");$("#notifyBtn").onclick=enableNotify;$("#cloudConnect").onclick=setupCloud;$("#cloudSync").onclick=()=>cloudPull(true);$("#closeModal").onclick=()=>$("#modal").classList.add("hidden");$("#backupBtn").onclick=backup;$("#restoreInput").onchange=e=>{if(e.target.files[0])restore(e.target.files[0])};
$("#globalSearch").oninput=e=>{const q=e.target.value.trim().toLowerCase();if(!q)return;const found=[...db.finance.map(x=>["finance",x.title]),...db.tasks.map(x=>["tasks",x.title]),...db.reminders.map(x=>["reminders",x.title]),...db.shopping.map(x=>["shopping",x.title]),...db.inventory.map(x=>["inventory",x.title]),...db.notes.map(x=>["notes",x.title]),...db.fish.map(x=>["fish",`${x.name} ${x.species} ${x.pattern}`])].find(x=>x[1].toLowerCase().includes(q));if(found)show(found[0])};
$("#today").textContent=new Date().toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"});
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
setInterval(checkReminders,30000);render();checkReminders();if(cloudConfigured())setTimeout(()=>cloudPull(false),1200);setInterval(()=>{if(document.visibilityState==="visible"&&cloudConfigured())cloudPull(false)},30000);
